source 'https://rubygems.org'

gem 'activerecord'
gem 'byebug'
gem 'dotenv'
gem 'openai'
gem 'pdf-reader'
gem 'rack', '>= 3.1.3', '< 3.2.0'
gem 'rackup'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-cors'
gem 'sqlite3', '~> 1.4'
